name: CI/CD MLOps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ”„ Cloner le dÃ©pÃ´t
        uses: actions/checkout@v3

      - name: ğŸ—ï¸ Installer Python et dÃ©pendances
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: ğŸ“¦ Installer les dÃ©pendances
        run: |
          make install

      - name: ğŸ” VÃ©rification du code
        run: |
          make check

      - name: ğŸ› ï¸ ExÃ©cuter les tests unitaires
        run: |
          make test

      - name: ğŸ”„ ExÃ©cuter le pipeline ML
        run: |
          make prepare
          make train
          make evaluate

      - name: ğŸ“¤ Sauvegarde du modÃ¨le
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: models/model.joblib
